### ISSUE TITLE
create default set of tests for your application during setup

### ISSUE THREAD

**Issue by alexfarrill** [psugihara/mailing#39]
At the same time as scaffolding the emails directory, it would be nice if it added a `__tests__/emails` directory with a default set of tests.  wdyt?

**Comment by psugihara** [comment]
2 thoughts, one on "why" and one on "how"

1. I think integration tests with the emails are really useful (e.g. I hit this endpoint and it sends an email with content matching X), but I wonder about the efficacy of unit testing the templates themselves since they just render to static html can't really have much logic. I'm sure there are edge case complicated templates where it makes more sense but I doubt you'd want a unit test for each template.
2. Maybe more importantly, it seems technically hard to implement in a portable way... a lot of people will have their js projects set up to run __tests__ colocated with the ts but we don't know which test runner they use (vitest, jest, etc). We could ship with a test-runner (`mailing test`) and tests written against that runner, but you'd probably have to add an ignore to the existing runner. Another possibility could be checking their test runner on init.

**Comment by psugihara** [comment]
I def like the thrust of seeding with best practices, but this one is tricky because it kind of sits on the boundary of what the email utility should do vs the web framework.

**Comment by alexfarrill** [comment]
True, unit tests not that useful in this context, frameworks will vary.  Let's close for now
